### ISSUE TITLE
Differences between nginx?

### ISSUE THREAD

**Issue by abacaj** [mortie/tlsproxy#1]
Hey just wanted to first say nice project. How is this different when compared to lets say nginx? Is it supposed to be more 'lightweight' or more 'performant'?

For example you can setup SSL certificates using this tutorial on nginx https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04

Also do you have any performance benchmarks using your reverse proxy / server?

**Comment by mortie** [comment]
Setting up automatic SSL with nginx requires a lot of configuration. I wanted to build something which "just works"; you just have to replace `http://` with `https://` in the `host` field, and suddenly https is completely configured. It also requires less configuration in general; e.g adding a redirect from http to https is literally one line ("redirectFrom": "http://example.com"). Being able to confiruge the server to start the processes it's a reverse proxy for is also a feature which is useful to me, and doesn't exist in nginx.

I would imagine it's slower than nginx due to being javascript and all, but haven't done any benchmarks. I'll probably get around to doing that soon-ish.
